export { DynamoDBModule } from './module/dynamodb.module'
export { InjectDDBModel, ReturnDDBModel } from './module/dynamodb.decorators'
export {
  attribute,
  hashKey,
  rangeKey,
  table,
  autoGeneratedHashKey,
  versionAttribute,
} from '@aws/dynamodb-data-mapper-annotations'
